# Generated by Django 3.2.3 on 2021-05-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorprofile',
            name='pimage',
        ),
    ]
