# Generated by Django 3.2.3 on 2021-05-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0002_remove_investorprofile_pimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideaname', models.CharField(max_length=100)),
                ('usermail', models.CharField(max_length=100)),
            ],
        ),
    ]
