# Generated by Django 3.2.3 on 2021-05-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0003_idealikes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='idealikes',
            table='idealikes',
        ),
    ]
